# Generated by Django 3.2.18 on 2023-04-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20230405_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='background_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
