# Generated by Django 3.2.18 on 2023-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20230417_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
