# Generated by Django 3.2.18 on 2023-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20230417_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Military', 'Military'), ('Social', 'Social'), ('Political', 'Political'), ('Economic', 'Economic'), ('Technological', 'Technological'), ('Intellectual', 'Intellectual'), ('Environmental', 'Environmental'), ('Medical', 'Medical'), ('Artistic', 'Artistic'), ('Religious', 'Religious')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
