# Generated by Django 3.2.18 on 2023-04-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20230419_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='about',
        ),
    ]
