# Generated by Django 3.2.18 on 2023-04-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20230422_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
