# Generated by Django 3.2.18 on 2023-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='images/default_profile_pic.png', upload_to='profile_pictures/'),
        ),
    ]
