# Generated by Django 4.2 on 2023-05-06 14:12

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
