# Generated by Django 4.2 on 2023-05-08 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_post_image_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=33.6573),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=-118.0059),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
