# Generated by Django 4.2 on 2023-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_post_user_category_delete_usercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_defined_categories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('military', 'Military'), ('social', 'Social'), ('political', 'Political'), ('economic', 'Economic'), ('technological', 'Technological'), ('intellectual', 'Intellectual'), ('environmental', 'Environmental'), ('medical', 'Medical'), ('artistic', 'Artistic'), ('religious', 'Religious'), ('sports', 'Sports')], max_length=50, null=True),
        ),
    ]
