# Generated by Django 4.2 on 2023-05-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_post_user_defined_categories_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_defined_categories',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='memory_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
