# Generated by Django 4.2 on 2023-05-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_rename_user_defined_categories_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='include_time',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='time_optional',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='memory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
