# Generated by Django 4.2 on 2023-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_post_include_time_post_time_optional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='include_time',
            field=models.BooleanField(default=False),
        ),
    ]
