# Generated by Django 4.2 on 2023-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_rename_time_optional_post_time_post_decade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6, null=True),
        ),
    ]
