# Generated by Django 4.2 on 2023-05-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_post_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='images/default-profile.png', upload_to='profile_pictures/'),
        ),
    ]
