# Generated by Django 4.2 on 2023-05-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_post_season_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memory_date',
            new_name='memory_end_date',
        ),
        migrations.AddField(
            model_name='post',
            name='memory_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
