# Generated by Django 4.2 on 2023-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_rename_memory_date_post_memory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_range',
            field=models.BooleanField(default=False),
        ),
    ]
